apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command:
            [
              'sh',
              '-c',
              'until nc -z nats-srv 8222; do echo "Waiting for NATS..."; sleep 5; done;',
            ]
      containers:
        - name: ticket-service
          image: bmate11/ticket-service
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://ticket-service-mongo-srv:27017/ticket-service'
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service-srv
spec:
  selector:
    app: ticket-service
  ports:
    - name: ticket-service
      protocol: TCP
      port: 3000
      targetPort: 3000
